Add tests for TaskController
brayvasq/jiffy pull request #11
Opened 2021-03-26 04:00 UTC by JoseCastroA

# :bulb: Type of change
- [ ] bugfix :bug:.
- [x] new feature.
- [ ] refactoring.

# :notebook: Description
In this PR I added basic tests for TaskController

# :bomb: How Has This Been Tested?

2021-03-28 21:54 UTC, brayvasq requested changes

2021-03-28 21:54 UTC, brayvasq commented on Gemfile
> +  gem 'rails-controller-testing'
@JoseCastroA What's the purpose of this gem?

2021-03-28 21:54 UTC, brayvasq commented on spec/controllers/api/v1/tasks_controller_spec.rb
> +      expect(subject.status).to eq(200)
@JoseCastroA I think this kind of tests could be written as follows:
```ruby
it { is_expected.to have_http_status(:ok) }
```

2021-03-28 21:54 UTC, brayvasq commented on spec/controllers/api/v1/tasks_controller_spec.rb
> +    it 'when there are not tasks' do
@JoseCastroA I think this example should be in a different context, something like the following
```ruby
describe 'GET index' do
  context 'when there are not tasks' do
    # this example.
  end

  context 'when there are tasks' do
    let!(:tasks) { .... }

    # Examples for success case.
  end
end
```

2021-03-28 21:54 UTC, brayvasq commented on spec/controllers/api/v1/tasks_controller_spec.rb
> +      let(:params) { { task: { title: Faker::Hacker.say_something_smart, description: Faker::Hacker.adjective, time: Faker::Number.number(digits: 3) } } }
@JoseCastroA This line is too long.

2021-03-31 03:23 UTC, JoseCastroA commented
@brayvasq Changes are ready

2021-03-31 23:09 UTC, brayvasq requested changes

2021-03-31 23:09 UTC, brayvasq commented on spec/controllers/api/v1/tasks_controller_spec.rb
> +      context 'when data is provided is valid' do
@JoseCastroA I think we don't need this context.

2021-03-31 23:09 UTC, brayvasq commented on spec/controllers/api/v1/tasks_controller_spec.rb
> +      let!(:tasks) { create_list(:task, 10) }
**praise:** Good use of `let!`

2021-04-04 01:25 UTC, JoseCastroArias commented
@brayvasq Changes are ready.

2021-04-04 19:25 UTC, brayvasq approved these changes

2021-04-04 19:25 UTC, merged